const categories: string[] = [
    "Acción",
    "Artes Marciales",
    "Aventuras",
    "Carreras",
    "Ciencia Ficción",
    "Comedia",
    "Demencia",
    "Demonios",
    "Deportes",
    "Drama",
    "Ecchi",
    "Escolares",
    "Espacial",
    "Fantasía",
    "Harem",
    "Histórico",
    "Infantil",
    "Josei",
    "Juegos",
    "Magia",
    "Mecha",
    "Militar",
    "Misterio",
    "Música",
    "Parodia",
    "Policía",
    "Psicológico",
    "Recuentos de la Vida",
    "Romance",
    "Samurai",
    "Seinen",
    "Shoujo",
    "Shounen",
    "Sobrenatural",
    "Superpoderes",
    "Suspenso",
    "Terror",
    "Vampiros",
    "Yaoi",
    "Yuri",
];
export default categories
